# Introducción a Numpy

[Numpy](https://numpy.org/doc/stable/) es una biblioteca fundamental para la computación científica con Python.

* Proporciona arrays N-dimensionales.
* Implementa funciones matemáticas sofisticadas.
* Proporciona herramientas para integrar C/C++ y Fortran.
* Proporciona mecanismos para facilitar la realización de tareas relacionadas con álgebra lineal o números aleatorios.

## Import

In [2]:
import numpy as np

## Arrays

Un **array** es una estructura de datos que consiste en una selección de elementos (valores o variables), cada uno identificado por al menos un índice o clave. Un array se almacena de modo que la posición de cada elemento se pueda calcular a partir de su tupla de indice mediante su fórmula matemática. El tipo más simple de array es un array lineal, tambien llamado array unidimensional.

En Numpy:
* Cada dimensión se denomina **axis**.
* El número de dimensiones se denomina **rank**.
* La lista de dimensiones con su correspondente longitud se denomina *+shape**.
* El número total de elementos (multiplicación de la longitud de las dimensiones), se denomina **size**.



In [3]:
a = np.zeros((2,4))
a 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**a** es un array:

* Con dos **axis**, la primera de longitud 2 y el segundo de longitud 4.
* Con un **rank** igual a 2.
* Con un **Shape** igual (2,4).
* Con un **Size** igual a 8.

In [4]:
a.shape

(2, 4)

In [5]:
a.ndim

2

In [6]:
a.size

8

## Creación de Arrays

In [7]:
# Array cuyos valores son todos 0.
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
# Array cuyos valore son todos 1.
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [9]:
# Array cuyos valores son todos el valor indicado como segundo parámetro de la función
np.full((2, 3, 4), 8)

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [10]:
# Eñ resultado de np.empty no es predecible.
# Inicializa los valores del Array con lo que hay en la memoria en ese momento.
np.empty((2, 3, 9))

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [13]:
# Inicializando el Array utilizando un array de Python.
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
b.shape

(2, 3)

In [15]:
# Crear un array utilizando una función basada en rangos.
# (Minimo, Maximo, Número de elementos del Array)
print(np.linspace(0, 6, 10))

[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]
